apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-app
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-flink
automountServiceAccountToken: true
