#!/usr/bin/env bash
# Generate or refresh the per-deployment configuration the demo overlay expects.
#
#   infra/.env                           Compose variables, including DEMO_BASE_URL
#   infra/secrets/feedback_api_key.txt   API key for the feedback service
#   infra/caddy/auth.conf                bcrypt basic_auth block for the proxy
#
# Modes:
#   (default)         Generate everything. Refuses to overwrite an existing setup.
#   --force           Regenerate everything, rotating every credential.
#   --base-url-only   Rewrite DEMO_BASE_URL and leave all credentials alone.
#
# --base-url-only exists because a stopped EC2 instance gets a new public IP on
# every start. The address has to be refreshed, but rotating the Grafana password
# and API key at the same time would invalidate credentials already handed to an
# evaluator.
#
# Usage:
#   scripts/deploy/make-secrets.sh
#   scripts/deploy/make-secrets.sh --force
#   scripts/deploy/make-secrets.sh --base-url-only
#   scripts/deploy/make-secrets.sh --base-url-only --base-url http://203.0.113.10

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FORCE=0
BASE_URL_ONLY=0
BASE_URL=""

usage() {
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --base-url-only) BASE_URL_ONLY=1; shift ;;
    --base-url) BASE_URL="${2:-}"; [[ -n "$BASE_URL" ]] || { echo "--base-url needs a value" >&2; exit 2; }; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "Unknown argument: $1" >&2; usage 2 ;;
  esac
done

if [[ $FORCE -eq 1 && $BASE_URL_ONLY -eq 1 ]]; then
  echo "--force and --base-url-only are mutually exclusive." >&2
  exit 2
fi

ENV_FILE="$REPO_ROOT/infra/.env"
API_KEY_FILE="$REPO_ROOT/infra/secrets/feedback_api_key.txt"
AUTH_FILE="$REPO_ROOT/infra/caddy/auth.conf"

random_secret() {
  # 32 URL-safe characters. Stripping +/= keeps the value safe to paste into a
  # shell, a .env line, and an HTTP header without quoting surprises.
  openssl rand -base64 48 | tr -d '\n+/=' | cut -c1-32
}

detect_base_url() {
  # IMDSv2 requires a token; fall back cleanly when running outside EC2.
  local token public_ip
  token="$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60" --connect-timeout 2 2>/dev/null || true)"
  if [[ -n "$token" ]]; then
    public_ip="$(curl -fsS -H "X-aws-ec2-metadata-token: $token" \
      "http://169.254.169.254/latest/meta-data/public-ipv4" --connect-timeout 2 2>/dev/null || true)"
    if [[ -n "$public_ip" ]]; then
      echo "http://$public_ip"
      return
    fi
  fi
  echo ""
}

resolve_base_url() {
  if [[ -z "$BASE_URL" ]]; then
    BASE_URL="$(detect_base_url)"
  fi
  if [[ -z "$BASE_URL" ]]; then
    echo "Could not determine the public address. Pass --base-url http://<host>." >&2
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Address-only refresh
# ---------------------------------------------------------------------------

if [[ $BASE_URL_ONLY -eq 1 ]]; then
  [[ -f "$ENV_FILE" ]] || { echo "infra/.env does not exist. Run without --base-url-only first." >&2; exit 1; }
  resolve_base_url

  current="$(grep -E '^DEMO_BASE_URL=' "$ENV_FILE" | cut -d= -f2- || true)"
  if [[ "$current" == "$BASE_URL" ]]; then
    echo "DEMO_BASE_URL is already $BASE_URL. Nothing to do."
    exit 0
  fi

  # '|' as the delimiter because the replacement is a URL containing '/'.
  if grep -qE '^DEMO_BASE_URL=' "$ENV_FILE"; then
    sed -i "s|^DEMO_BASE_URL=.*|DEMO_BASE_URL=$BASE_URL|" "$ENV_FILE"
  else
    echo "DEMO_BASE_URL=$BASE_URL" >> "$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE"

  echo "DEMO_BASE_URL updated."
  echo "  was  ${current:-<unset>}"
  echo "  now  $BASE_URL"
  echo
  echo "Credentials are unchanged. Restart the affected services to pick it up:"
  echo "  scripts/deploy/start-demo.sh"
  exit 0
fi

# ---------------------------------------------------------------------------
# Full generation
# ---------------------------------------------------------------------------

if [[ $FORCE -eq 0 && -f "$ENV_FILE" ]]; then
  cat >&2 <<'EOF'
infra/.env already exists.

  To refresh only the public address after a restart, keeping every credential:
    scripts/deploy/make-secrets.sh --base-url-only

  To rotate every credential and start over:
    scripts/deploy/make-secrets.sh --force
EOF
  exit 1
fi

resolve_base_url

POSTGRES_PASSWORD="$(random_secret)"
GRAFANA_ADMIN_PASSWORD="$(random_secret)"
FEEDBACK_API_KEY="$(random_secret)"
DEMO_USER="evaluator"
DEMO_PASSWORD="$(random_secret)"

mkdir -p "$REPO_ROOT/infra/secrets" "$REPO_ROOT/infra/caddy"

# caddy hash-password runs in the same image the proxy uses, so no local Caddy is needed.
DEMO_PASSWORD_HASH="$(docker run --rm caddy:2.8-alpine \
  caddy hash-password --plaintext "$DEMO_PASSWORD")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy/make-secrets.sh. Never commit this file.
APP_ENV=production
DEMO_BASE_URL=$BASE_URL
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
DEMO_TRAFFIC_RATE=8
DEMO_FRAUD_RATIO=0.04
EOF

printf '%s' "$FEEDBACK_API_KEY" > "$API_KEY_FILE"

cat > "$AUTH_FILE" <<EOF
basic_auth {
	$DEMO_USER $DEMO_PASSWORD_HASH
}
EOF

chmod 600 "$ENV_FILE" "$API_KEY_FILE" "$AUTH_FILE"

cat <<EOF

Credentials generated. Record these now; the plaintext is not stored anywhere.

  Demo URL          $BASE_URL
  Grafana           admin / $GRAFANA_ADMIN_PASSWORD
  Proxy basic auth  $DEMO_USER / $DEMO_PASSWORD
  Feedback API key  $FEEDBACK_API_KEY

Prometheus, MLflow, and the Flink REST path sit behind the proxy basic auth.
Grafana keeps its own separate login.

After a stop and start the public IP changes. Refresh it without rotating any
of the above:
  scripts/deploy/make-secrets.sh --base-url-only
EOF
