#!/usr/bin/env bash
# Generate the per-deployment secrets the demo overlay expects.
#
#   infra/.env                      Compose variables, including DEMO_BASE_URL
#   infra/secrets/feedback_api_key.txt   API key for the feedback service
#   infra/caddy/auth.conf           bcrypt basic_auth block for the proxy
#
# Existing files are left alone unless --force is passed, so re-running after a
# reboot does not silently invalidate credentials already handed to an evaluator.
#
# Usage:
#   scripts/deploy/make-secrets.sh [--force] [--base-url http://example.com]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
FORCE=0
BASE_URL=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --base-url) BASE_URL="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

ENV_FILE="$REPO_ROOT/infra/.env"
API_KEY_FILE="$REPO_ROOT/infra/secrets/feedback_api_key.txt"
AUTH_FILE="$REPO_ROOT/infra/caddy/auth.conf"

if [[ $FORCE -eq 0 && -f "$ENV_FILE" ]]; then
  echo "infra/.env already exists. Re-run with --force to regenerate all credentials." >&2
  exit 1
fi

random_secret() {
  # 32 URL-safe bytes. tr -d avoids '+' and '/' leaking into shell-quoted contexts.
  openssl rand -base64 48 | tr -d '\n+/=' | cut -c1-32
}

detect_base_url() {
  # IMDSv2 requires a token; fall back cleanly when running outside EC2.
  local token public_ip
  token="$(curl -fsS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60" --connect-timeout 2 2>/dev/null || true)"
  if [[ -n "$token" ]]; then
    public_ip="$(curl -fsS -H "X-aws-ec2-metadata-token: $token" \
      "http://169.254.169.254/latest/meta-data/public-ipv4" --connect-timeout 2 2>/dev/null || true)"
    if [[ -n "$public_ip" ]]; then
      echo "http://$public_ip"
      return
    fi
  fi
  echo ""
}

if [[ -z "$BASE_URL" ]]; then
  BASE_URL="$(detect_base_url)"
fi

if [[ -z "$BASE_URL" ]]; then
  echo "Could not determine the public address. Pass --base-url http://<host>." >&2
  exit 1
fi

POSTGRES_PASSWORD="$(random_secret)"
GRAFANA_ADMIN_PASSWORD="$(random_secret)"
FEEDBACK_API_KEY="$(random_secret)"
DEMO_USER="evaluator"
DEMO_PASSWORD="$(random_secret)"

mkdir -p "$REPO_ROOT/infra/secrets" "$REPO_ROOT/infra/caddy"

# caddy hash-password runs in the same image the proxy uses, so no local Caddy is needed.
DEMO_PASSWORD_HASH="$(docker run --rm caddy:2.8-alpine \
  caddy hash-password --plaintext "$DEMO_PASSWORD")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy/make-secrets.sh. Never commit this file.
APP_ENV=production
DEMO_BASE_URL=$BASE_URL
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
DEMO_TRAFFIC_RATE=8
DEMO_FRAUD_RATIO=0.04
EOF

printf '%s' "$FEEDBACK_API_KEY" > "$API_KEY_FILE"

cat > "$AUTH_FILE" <<EOF
basic_auth {
	$DEMO_USER $DEMO_PASSWORD_HASH
}
EOF

chmod 600 "$ENV_FILE" "$API_KEY_FILE" "$AUTH_FILE"

cat <<EOF

Credentials generated. Record these now; the plaintext is not stored anywhere.

  Demo URL          $BASE_URL
  Grafana           admin / $GRAFANA_ADMIN_PASSWORD
  Proxy basic auth  $DEMO_USER / $DEMO_PASSWORD
  Feedback API key  $FEEDBACK_API_KEY

Prometheus, MLflow, and the Flink REST path sit behind the proxy basic auth.
Grafana keeps its own separate login.
EOF
